name: 从fofa获取组播IP

on:
  #schedule:
    #- cron: "0 20 * * *"
  push:
    branches:
      - main # 只在master上push触发部署
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: 代码检出
      uses: actions/checkout@v3
      
    #- name: 安装插件
      #run: |
        #sudo apt-get update
        #sudo apt-get install -y yt-dlp sed nmap
   
    - name: Install FFmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg
      
    - name: 运行脚本
      #working-directory: iptv/speedtest
      run: |
        #cd $GITHUB_WORKSPACE/speedtest
        #chmod +x speed.sh
        bash ./fofa_zubo.sh
        
    - name: 缓存运行结果
      uses: actions/upload-artifact@v4
      with:
          name: cache
          path: speedtest/
          
    - name: 提交更改
      run: |
        #cd $GITHUB_WORKSPACE/speedtest
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "更新组播IP"
        git push -f
