name: 复制iptvz并合并

on:
  schedule:
    - cron: '0 */8 * * *'
  #push:
    #branches:
      #- main  # 触发工作流的分支
  workflow_dispatch:  # 也可以手动触发

jobs:
  copy-folder:
    runs-on: ubuntu-latest

    steps:
      - name: 代码检出
        uses: actions/checkout@v3

      - name: 设置Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
        
        #q1017673817/iptvz/
      - name: 复制源仓库
        run: |
          git clone --depth 1 https://github.com/q1017673817/iptvz.git source-repo
          # 替换OWNER和REPOSITORY为源仓库的拥有者和仓库名称

      - name: 复制文件夹
        run: |
          mkdir -p txt/q1017673817/iptvz
          cp -r source-repo/txt ./txt/q1017673817/iptvz
          # 替换PATH/TO/FOLDER为源仓库中的目标文件夹路径
          # 替换YOUR/DESTINATION为你仓库中要复制到的目标路径



      - name: 合并到zubo_iptvz.txt
        run: |
            output_file="itv.txt"
            rm -rf "$output_file"
            echo "===============合并所有城市的txt文件为:zubo_fofa.txt================="
            provinces_cn=(
                "江苏" "上海" "浙江" "安徽" "福建" "江西" "山东"
                "北京" "天津" "河北" "山西" "内蒙古"
                "辽宁" "吉林" "黑龙江"
                "河南" "湖北" "湖南" "广东" "广西" "海南"
                "重庆" "四川" "贵州" "云南" "西藏"
                "陕西" "甘肃" "青海" "宁夏" "新疆"
            )

            for province_cn in "${provinces_cn[@]}"; do
                for file in txt/q1017673817/iptvz/txt/"$province_cn"*.txt;do
                    if [ ! -s "${file}" ]; then
                        echo "$file文件为空，不添加"
                        continue
                    fi
                    echo "添加$file"
                    #filename=$(basename "$file")
                    filename=$(basename "$file" | sed 's/_/-/g' | sed 's/fofa-//g' | sed 's/.txt//g')
                    echo "$filename,#genre#" >> "$output_file"
                    #cat "$file" >> "$output_file"
                    #删除包含#的行
                    sed '/#/c\\n' "$file" >> "$output_file"

                    echo "" >> "$output_file"
                done
            done
    
      - name: 提交更新
        run: |
          git add .
          git commit -m "Copy folder from another repository" || true
          git push origin main
