name: 获取组播IP

on:
  #schedule:
    #- cron: "0 20 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y yt-dlp sed nmap
      
    - name: Run Multitest Script
      #working-directory: iptv/speedtest
      run: |
        cd $GITHUB_WORKSPACE/speedtest
        chmod +x speed.sh
        #bash ./multi_test.sh
        bash ./fofa.sh
    - name: cache file
      uses: actions/upload-artifact@v4
      with:
          name: cache
          path: $GITHUB_WORKSPACE/speedtest
    - name: Update Results
      run: |
        cd $GITHUB_WORKSPACE/speedtest
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update results"
        git push
